version: '3'
services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=seu_usuario
      - N8N_BASIC_AUTH_PASSWORD=sua_senha
    volumes:
      - ./data:/home/node/.n8n
    networks:
      - appnetwork
  postgres-compose:
        container_name: postgres-exemplo
        image: postgres:13
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=sysdb
            - POSTGRES_DB=postgres
            - TZ=GMT
        ports:
            - 15432:5432
        volumes:
            - ./.docker/data/postgres:/var/lib/postgresql/data
        networks:
            - appnetwork
networks:
    appnetwork:
        driver: bridge
